// Code generated by goctl. DO NOT EDIT.
// Source: reply.proto

package server

import (
	"context"

	"lifememo/application/reply/rpc/internal/logic"
	"lifememo/application/reply/rpc/internal/svc"
	"lifememo/application/reply/rpc/pb1"
)

type ReplyServer struct {
	svcCtx *svc.ServiceContext
	pb1.UnimplementedReplyServer
}

func NewReplyServer(svcCtx *svc.ServiceContext) *ReplyServer {
	return &ReplyServer{
		svcCtx: svcCtx,
	}
}

func (s *ReplyServer) Publish(ctx context.Context, in *pb1.PublishRequest) (*pb1.PublishResponse, error) {
	l := logic.NewPublishLogic(ctx, s.svcCtx)
	return l.Publish(in)
}

func (s *ReplyServer) ReplyList(ctx context.Context, in *pb1.ReplyListRequest) (*pb1.ReplyListResponse, error) {
	l := logic.NewReplyListLogic(ctx, s.svcCtx)
	return l.ReplyList(in)
}

func (s *ReplyServer) ReplyDetail(ctx context.Context, in *pb1.ReplyDetailRequest) (*pb1.ReplyDetailResponse, error) {
	l := logic.NewReplyDetailLogic(ctx, s.svcCtx)
	return l.ReplyDetail(in)
}

func (s *ReplyServer) FindReply(ctx context.Context, in *pb1.FindReplyRequest) (*pb1.FindReplyResponse, error) {
	l := logic.NewFindReplyLogic(ctx, s.svcCtx)
	return l.FindReply(in)
}
