// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"lifememo/application/follow/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/followuser",
				Handler: followUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/unfollowuser",
				Handler: unfollowUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/getfollowlist",
				Handler: getFollowListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/getfanslist",
				Handler: getFansListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1/follow"),
	)
}
