// Code generated by goctl. DO NOT EDIT.
// Source: like.proto

package like

import (
	"context"

	"lifememo/application/like/rpc/service"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	IsThumbupedRequest  = service.IsThumbupedRequest
	IsThumbupedResponse = service.IsThumbupedResponse
	ThumbupRequest      = service.ThumbupRequest
	ThumbupResponse     = service.ThumbupResponse

	Like interface {
		Thumbup(ctx context.Context, in *ThumbupRequest, opts ...grpc.CallOption) (*ThumbupResponse, error)
		IsThumbuped(ctx context.Context, in *IsThumbupedRequest, opts ...grpc.CallOption) (*IsThumbupedResponse, error)
	}

	defaultLike struct {
		cli zrpc.Client
	}
)

func NewLike(cli zrpc.Client) Like {
	return &defaultLike{
		cli: cli,
	}
}

func (m *defaultLike) Thumbup(ctx context.Context, in *ThumbupRequest, opts ...grpc.CallOption) (*ThumbupResponse, error) {
	client := service.NewLikeClient(m.cli.Conn())
	return client.Thumbup(ctx, in, opts...)
}

func (m *defaultLike) IsThumbuped(ctx context.Context, in *IsThumbupedRequest, opts ...grpc.CallOption) (*IsThumbupedResponse, error) {
	client := service.NewLikeClient(m.cli.Conn())
	return client.IsThumbuped(ctx, in, opts...)
}
