// Code generated by goctl. DO NOT EDIT.
package types

type ThumbUpRequest struct {
	BizId    string `json:"biz_id"`
	ObjId    int64  `json:"obj_id"`
	LikeType int32  `json:"like_type"`
}

type ThumbUpResponse struct {
}
