// Code generated by goctl. DO NOT EDIT.
package types

type ReplyItem struct {
	ReplyId         int64  `json:"reply_id"`
	BizId           string `json:"biz_id"`
	TargetId        int64  `json:"target_id"`
	ReplyUserId     int64  `json:"reply_user_id"`
	BeRepliedUserId int64  `json:"be_replied_user_id"`
	ParentId        int64  `json:"parent_id"`
	Content         string `json:"content"`
	Status          int64  `json:"status"`
	CreateTime      int64  `json:"create_time"`
	UpdateTime      int64  `json:"update_time"`
	LikeNum         int64  `json:"like_num"`
}

type RootReplyItem struct {
	ReplyId         int64        `json:"reply_id"`
	BizId           string       `json:"biz_id"`
	TargetId        int64        `json:"target_id"`
	ReplyUserId     int64        `json:"reply_user_id"`
	BeRepliedUserId int64        `json:"be_replied_user_id"`
	ParentId        int64        `json:"parent_id"`
	Content         string       `json:"content"`
	Status          int64        `json:"status"`
	CreateTime      int64        `json:"create_time"`
	UpdateTime      int64        `json:"update_time"`
	LikeNum         int64        `json:"like_num"`
	ReplyItems      []*ReplyItem `json:"reply_items"`
}

type CommentPublishRequest struct {
	BizId       string `json:"biz_id"`
	TargetId    int64  `json:"target_id"`
	BeRepliedId int64  `json:"be_replied_id"`
	ParentId    int64  `json:"parent_id"`
	Content     string `json:"content"`
	Status      int64  `json:"status"`
}

type CommentPublishResponse struct {
	Id int64 `json:"id"`
}

type CommentListRequest struct {
	BizId    string `json:"biz_id"`
	TargetId int64  `json:"target_id"`
	Cursor   int64  `json:"cursor"`
	PageSize int32  `json:"page_size"`
	SortType int32  `json:"sort_type"`
	ReplyId  int64  `json:"reply_id"`
}

type CommentListResponse struct {
	ReplyItems []*RootReplyItem `json:"reply_items"`
	Cursor     int64            `json:"cursor"`
	IsEnd      bool             `json:"is_end"`
	ReplyId    int64            `json:"reply_id"`
}

type CommentDetailRequest struct {
	ReplyId int64 `json:"reply_id"`
}

type CommentDetailResponse struct {
	ReplyItem *RootReplyItem `json:"reply_item"`
}
