// Code generated by goctl. DO NOT EDIT.
package types

type FollowItem struct {
	FollowedUserId int64 `json:"followed_user_id"`
	FansCount      int64 `json:"fans_count"`
	CreateTime     int64 `json:"create_time"`
}

type FansItem struct {
	FansUserId int64 `json:"fans_user_id"`
	FansCount  int64 `json:"follow_count"`
	CreateTime int64 `json:"create_time"`
}

type FollowRequest struct {
	FollowedUserId int64 `json:"followed_user_id"`
}

type FollowResponse struct {
}

type UnfollowRequest struct {
	FollowedUserId int64 `json:"followed_user_id"`
}

type UnfollowResponse struct {
}

type GetFollowListRequest struct {
	UserId   int64 `json:"user_id"`
	Cursor   int64 `json:"cursor"`
	PageSize int64 `json:"page_size"`
	Id       int64 `json:"id"`
}

type GetFollowListResponse struct {
	FollowList []*FollowItem `json:"follow_list"`
	Cursor     int64         `json:"cursor"`
	IsEnd      bool          `json:"is_end"`
	Id         int64         `json:"id"`
}

type GetFansListRequest struct {
	UserId   int64 `json:"user_id"`
	Cursor   int64 `json:"cursor"`
	PageSize int64 `json:"page_size"`
	Id       int64 `json:"id"`
}

type GetFansListResponse struct {
	FansList []*FansItem `json:"fans_list"`
	Cursor   int64       `json:"cursor"`
	IsEnd    bool        `json:"is_end"`
	Id       int64       `json:"id"`
}
