// Code generated by goctl. DO NOT EDIT.
// Source: message.proto

package server

import (
	"context"

	"lifememo/application/message/rpc/internal/logic"
	"lifememo/application/message/rpc/internal/svc"
	"lifememo/application/message/rpc/pb"
)

type MessageServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMessageServiceServer
}

func NewMessageServiceServer(svcCtx *svc.ServiceContext) *MessageServiceServer {
	return &MessageServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *MessageServiceServer) SentMessage(ctx context.Context, in *pb.SentMessageRequest) (*pb.SentMessageResponse, error) {
	l := logic.NewSentMessageLogic(ctx, s.svcCtx)
	return l.SentMessage(in)
}

func (s *MessageServiceServer) GetMessages(ctx context.Context, in *pb.GetMessagesRequest) (*pb.GetMessagesResponse, error) {
	l := logic.NewGetMessagesLogic(ctx, s.svcCtx)
	return l.GetMessages(in)
}

func (s *MessageServiceServer) DeleteMessage(ctx context.Context, in *pb.DeleteMessageRequest) (*pb.DeleteMessageResponse, error) {
	l := logic.NewDeleteMessageLogic(ctx, s.svcCtx)
	return l.DeleteMessage(in)
}
