// Code generated by goctl. DO NOT EDIT.
package types

type Token struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
}

type RegisterRequest struct {
	Name             string `json:"name"`
	Email            string `json:"email"`
	VerificationCode string `json:"verification_code"`
}

type RegisterResponse struct {
	UserId int64 `json:"user_id"`
	Token  Token `json:"token"`
}

type VerificationRequest struct {
	Email string `json:"email"`
}

type VerificationResponse struct {
}

type LoginRequest struct {
	Email            string `json:"email"`
	VerificationCode string `json:"verification_code"`
}

type LoginResponse struct {
	UserId int64 `json:"userId"`
	Token  Token `json:"token"`
}

type UserInfoResponse struct {
	UserId   int64  `json:"user_id"`
	Username string `json:"username"`
}
