// Code generated by goctl. DO NOT EDIT.
// Source: reply.proto

package reply

import (
	"context"

	"lifememo/application/reply/rpc/pb1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FindReplyRequest    = pb1.FindReplyRequest
	FindReplyResponse   = pb1.FindReplyResponse
	PublishRequest      = pb1.PublishRequest
	PublishResponse     = pb1.PublishResponse
	ReplyDetailRequest  = pb1.ReplyDetailRequest
	ReplyDetailResponse = pb1.ReplyDetailResponse
	ReplyItem           = pb1.ReplyItem
	ReplyListRequest    = pb1.ReplyListRequest
	ReplyListResponse   = pb1.ReplyListResponse
	RootReplyItem       = pb1.RootReplyItem

	Reply interface {
		Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
		ReplyList(ctx context.Context, in *ReplyListRequest, opts ...grpc.CallOption) (*ReplyListResponse, error)
		ReplyDetail(ctx context.Context, in *ReplyDetailRequest, opts ...grpc.CallOption) (*ReplyDetailResponse, error)
		FindReply(ctx context.Context, in *FindReplyRequest, opts ...grpc.CallOption) (*FindReplyResponse, error)
	}

	defaultReply struct {
		cli zrpc.Client
	}
)

func NewReply(cli zrpc.Client) Reply {
	return &defaultReply{
		cli: cli,
	}
}

func (m *defaultReply) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	client := pb1.NewReplyClient(m.cli.Conn())
	return client.Publish(ctx, in, opts...)
}

func (m *defaultReply) ReplyList(ctx context.Context, in *ReplyListRequest, opts ...grpc.CallOption) (*ReplyListResponse, error) {
	client := pb1.NewReplyClient(m.cli.Conn())
	return client.ReplyList(ctx, in, opts...)
}

func (m *defaultReply) ReplyDetail(ctx context.Context, in *ReplyDetailRequest, opts ...grpc.CallOption) (*ReplyDetailResponse, error) {
	client := pb1.NewReplyClient(m.cli.Conn())
	return client.ReplyDetail(ctx, in, opts...)
}

func (m *defaultReply) FindReply(ctx context.Context, in *FindReplyRequest, opts ...grpc.CallOption) (*FindReplyResponse, error) {
	client := pb1.NewReplyClient(m.cli.Conn())
	return client.FindReply(ctx, in, opts...)
}
