// Code generated by goctl. DO NOT EDIT.
package types

type MomentItem struct {
	Id           int64  `json:"id"`
	AuthorId     int64  `json:"author_id"`
	AuthorName   string `json:"author_name"`
	Content      string `json:"content"`
	CommentCount int64  `json:"comment_count"`
	LikeCount    int64  `json:"like_count"`
	PublishTime  int64  `json:"publish_time"`
}

type PublishRequest struct {
	Content string `json:"content"`
}

type PublishResponse struct {
	MonmentId int64 `json:"monment_id"`
}

type MomentsRequest struct {
	UserId   int64 `json:"user_id"`
	Cursor   int64 `json:"cursor"`
	PageSize int64 `json:"page_size"`
	SortType int32 `json:"sort_type"`
	MomentId int64 `json:"moment_id"`
}

type MomentsResponse struct {
	Moments  []*MomentItem `json:"moments"`
	Cursor   int64         `json:"cursor"`
	IsEnd    bool          `json:"is_end"`
	MomentId int64         `json:"moment_id"`
}

type MomentDetailRequest struct {
	MomentId int64 `json:"moment_id"`
}

type MomentDetailResponse struct {
	Moment *MomentItem `json:"moment"`
}

type MomentDeleteRequest struct {
	MomentId int64 `json:"moment_id"`
}

type MomentDeleteResponse struct {
}

type MomentUpdateRequest struct {
	MomentId int64  `json:"moment_id"`
	Content  string `json:"content"`
}

type MomentUpdateResponse struct {
}

type RandomMomentsResponse struct {
	Moments []*MomentItem `json:"moments"`
}
