// Code generated by goctl. DO NOT EDIT.
package types

type MessageItem struct {
	Id          int64  `json:"id"`
	SenderId    int64  `json:"sender_id"`
	ReceiverId  int64  `json:"receiver_id"`
	Content     string `json:"content"`
	CreatedTime int64  `json:"created_time"`
}

type SentMessageRequest struct {
	ReceiverId int64  `json:"receiver_id"`
	Content    string `json:"content"`
}

type SentMessageResponse struct {
	MessageId int64 `json:"message_id"`
}

type DeleteMessageRequest struct {
	MessageId int64 `json:"message_id"`
}

type DeleteMessageResponse struct {
}

type GetMessagesRequest struct {
	TargetId int64 `json:"target_id"`
}

type GetMessagesResponse struct {
	Messages []*MessageItem `json:"messages"`
}
