// Code generated by goctl. DO NOT EDIT.
// Source: message.proto

package messageservice

import (
	"context"

	"lifememo/application/message/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeleteMessageRequest  = pb.DeleteMessageRequest
	DeleteMessageResponse = pb.DeleteMessageResponse
	GetMessagesRequest    = pb.GetMessagesRequest
	GetMessagesResponse   = pb.GetMessagesResponse
	MessageItem           = pb.MessageItem
	SentMessageRequest    = pb.SentMessageRequest
	SentMessageResponse   = pb.SentMessageResponse

	MessageService interface {
		SentMessage(ctx context.Context, in *SentMessageRequest, opts ...grpc.CallOption) (*SentMessageResponse, error)
		GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error)
		DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*DeleteMessageResponse, error)
	}

	defaultMessageService struct {
		cli zrpc.Client
	}
)

func NewMessageService(cli zrpc.Client) MessageService {
	return &defaultMessageService{
		cli: cli,
	}
}

func (m *defaultMessageService) SentMessage(ctx context.Context, in *SentMessageRequest, opts ...grpc.CallOption) (*SentMessageResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.SentMessage(ctx, in, opts...)
}

func (m *defaultMessageService) GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.GetMessages(ctx, in, opts...)
}

func (m *defaultMessageService) DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*DeleteMessageResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.DeleteMessage(ctx, in, opts...)
}
